Some more tmux setup.

diff --git a/.tmux/compile_style b/.tmux/compile_style
--- a/.tmux/compile_style
+++ b/.tmux/compile_style
@@ -2,6 +2,11 @@
 
 # example: ./compile_style nord.style
 
+if [ -z $1 ]; then
+    echo "style file required --> nothing done"
+    exit 1
+fi
+
 ifs=$IFS
 IFSf=' '
 IFSl=' ='
